alias pipi='python3.7 -m pip install'
alias p='python3.7'
alias ds='python3.7 /opt/dirsearch/dirsearch.py -u'
alias arj='python3.7 /opt/Arjun/arjun.py -f /opt/Arjun/db/params.txt -u'
alias john='/opt/JohnTheRipper/run/john --wordlist=/opt/rockyou.txt'
alias sublist3r='python3.7 /opt/Sublist3r/sublist3r.py'
alias gdb='gdb -q'
alias r='ruby2.5'
alias docker='sudo docker'
